### aqui somente o file para postgres+ pdAdm sub no container
#services:
#  postgres:
#    container_name:  multirestaurant-postgres
#    image: postgres:15
#    environment:
#      POSTGRES_DB:  multirestaurant_db
#      POSTGRES_USER:  multirestaurant_user
#      POSTGRES_PASSWORD: adm1996
#    ports:
#      - "5032:5432"
#    volumes: ## aqui fican guardadas todas as tabelas
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - multirestaurant-network
#  pgadmin:
#    container_name:  multirestaurant-pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: adm@multirestaurant.com
#      PGADMIN_DEFAULT_PASSWORD: adm1996
#    ports:
#      - "5050:80"
#    depends_on:
#      - postgres
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    networks:
#      -  multirestaurant-network
#  backend:
#    container_name: multirestaurant-backend
#    build: .
#    ports:
#      - "8081:8080"
#    depends_on:
#      - postgres
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5032/multirestaurant_db
#      SPRING_DATASOURCE_USERNAME:  multirestaurant_user
#      SPRING_DATASOURCE_PASSWORD:adm1996
#    networks:
#      -  multirestaurant-network
#volumes:
#   postgres_data:
#   pgadmin_data:
#
#networks:
#   multirestaurant-network:
#     driver: bridge

# esta conf e somente para local o pgadm dentro do docker compose
# e minha api do meu back end subir localmente na porta 8081 caso quero fazer minha
## aplicacao prodar dentro docker compose preciso fazer build dela  e muda as portas

services:
  postgres:
    container_name: multirestaurant-postgres
    image: postgres:15
    environment:
      POSTGRES_DB: multirestaurant_db
      POSTGRES_USER: multirestaurant_user
      POSTGRES_PASSWORD: adm1996
    ports:
      - "5032:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: multirestaurant-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: adm@multirestaurant.com
      PGADMIN_DEFAULT_PASSWORD: adm1996
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: