#spring:
#  application:
#    name: MultiRestaurant Management API
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5032/multirestaurant_db
      username: multirestaurant_user
      password: adm1996
      driver-class-name: org.postgresql.Driver
      hikari:
        initializationFailTimeout: 60000

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  server:
    port: 8081

  # Configuração Swagger/OpenAPI
  springdoc:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html
      operations-sorter: method
      tags-sorter: alpha
    api-docs:
      path: /v3/api-docs

